<!doctype html>
<html lang="cn" ng-app='route_app'>
<head>
  <meta charset="utf-8">
  <title>HHA</title>
  <link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css" href="css/main-style.css">

  <script src="js/jquery/jquery.min.js"></script>
  <script src="bootstrap/js/bootstrap.min.js"></script>
  <script src="js/jquery/jquery.leanModal.min.js"></script>
  <script src="js/jquery/jquery.goup.min.js"></script>
  
  <script src="js/angular/angular.min.js"></script>
  <script src="js/angular/angular-route.min.js"></script>
  <script src="js/angular/angular-resource.min.js"></script>
  <script src="js/angular/angular-cookies.js"></script>
  
  <script src="js/index/index_controller.js"></script>
  <script src="js/login/login_page_controller.js"></script>
  <script src="js/index.js"></script>
  <script type="text/javascript">
  	window.onunload = function(){
  		
      if($cookieStore.get('is_auto_login')!=null && $cookieStore.get('is_auto_login') == 'false'){
        $.cookie
      }
  	};

  </script>

</head>

<body ng-controller='route_controller'>
  <div ng-include="top_url"></div>

	<div class = "container body-div"><div ng-view></div></div>
</body>
</html>